# Hairbrush configuration settings

# Default parameters for G-code generation
default_parameters:
  z_height: 2.0  # Distance from nozzle to paper in mm
  feedrate: 3000  # Movement speed in mm/min
  brush_a_layer: "black"  # Layer name for brush A
  brush_b_layer: "white"  # Layer name for brush B

# Path processing settings
path_processing:
  simplify_tolerance: 0.1  # Tolerance for path simplification
  segment_length: 1.0  # Maximum segment length for curve approximation

# Output settings
output:
  default_directory: "output"  # Default directory for G-code output
  file_extension: ".gcode"  # File extension for G-code files 